{
 "title": "API Detection",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_CLICKHOUSE", "label": "Clickhouse", "query": "grafana-clickhouse-datasource" },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT distinct host from api_detection.detected_api_endpoints"
   },
   { "name": "path_prefix", "label": "Path Prefix", "query": "/" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clickhouse Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otel Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"opentelemetry-collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Analyzer Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"log-analyzer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Analysis Time (Approx)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(Timestamp) as \"time\" FROM \"api_detection\".\"detected_api_endpoints\""
    }
   ]
  },
  {
   "title": "Logs Analyzed Last Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ladt_analysis_logs_last_processed_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Logs Since Last Analysis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ladt_analyisis_logs_pending_since_last_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System State Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Analysis Settings",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "targets": [
      { "expr": "ladt_settings_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Logs Last Processed By Host",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ladt_analysis_logs_last_processed_count",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Logs Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(exporter) (rate(otelcol_exporter_sent_log_records_total{exporter=\"clickhouse\"}[$__rate_interval]))",
       "legendFormat": "{{exporter}}"
      }
     ]
    },
    {
     "title": "Logs Processed At Last Analysis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ladt_analysis_logs_last_processed_count",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Last Analysis Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ladt_analysis_last_run_duration_seconds",
       "legendFormat": "Analysis Duration"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"log-analyzer\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum by(job) (rate(otelcol_process_cpu_seconds_total{job=\"opentelemetry-collector\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds[5m])/1000000",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ClickHouseAsyncMetrics_MemoryResident{job=\"clickhouse\"}",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum by(job) (otelcol_process_runtime_total_sys_memory_bytes{job=\"opentelemetry-collector\"})",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "process_resident_memory_bytes{job=\"log-analyzer\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "Detection Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Detection Results",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT path, host, method, isAuthenticated, accesses FROM \"api_detection\".\"detected_api_endpoints\" t1 WHERE Timestamp = (SELECT MAX(Timestamp) from \"api_detection\".\"detected_api_endpoints\" t2) AND host LIKE '${host}' AND startsWith(path, '$path_prefix' ) ORDER BY accesses DESC LIMIT 1000"
    }
   ]
  }
 ]
}